name: cvmatching

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.12
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - pytorch
  - streamlit
  - flask
  - nltk
  - pip
  - spacy-model-en_core_web_sm
  - spacy-model-en_core_web_lg
  - ipython<9 
  - jupyter
  - spacy
  - sentence-transformers
  - transformers
  - qdrant-client
  - gensim=4.3.3
  - pyyaml
  - PyPDF2
