name: cvmatching

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.12.7
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - pytorch
  - streamlit
  - flask
  - nltk
  - pip
  - spacy-model-en_core_web_sm
  - pip:
    - spacy
    # - word2vec
    - sentence-transformers
    - transformers
    - qdrant-client
    - nltk