name: cvmatching

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.13.7
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - pytorch
  - streamlit
  - flask
  - nltk
  - pip
  - pip:
    - spacy
    - word2vec
    - torch
    - sentence-transformers
    - transformers