name: cvmatching

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - pytorch
  - streamlit
  - flask
  - nltk
  - pip
  - ipython<9 
  - jupyter
  - spacy
  - sentence-transformers
  - transformers
  - qdrant-client
  - gensim=4.3.3
  - pyyaml
  - PyPDF2
  - peft
  - pip:
    - doccano