paths:
  raw_folder: "data/raw"
  processed_folder: "data/processed"
  model_folder: "models"

datasets:
  jobs:
    input_filename: 'job_descriptions2.csv'
    columns_to_process: ['Job Description', 'Preferred Skills', 'Business Title']
    duplicate_subset: ['Job ID']
    qdrant_collection_name: "job1_embeddings"
    qdrant_payload_columns: ["Job ID", "Business Title", "Job Category", "Division/Work Unit"]

  resumes:
    input_filename: 'Resume.csv'
    columns_to_process: ['Resume_str']
    duplicate_subset: null
    qdrant_collection_name: "resumes1_embeddings"
    qdrant_payload_columns: ["ID", "Category"]

preprocessing:
  use_lemmatization: true
  use_ner: true
  chunksize: 50000

training:
  epochs: 100
  alpha: 0.001
  vector_size: 384
  window: 5
  min_count: 1
  seed: 42

qdrant:
  url: "http://localhost:6333"
  timeout: 60
  batch_size: 256

evaluation:
  top_k: 10
