logging:
  file_name: "pipeline.log" # custom log file name

paths:
  raw_folder: "data/raw"
  processed_folder: "data/processed"
  models_folder: "models"

preprocessing:
  model_name: "all-mpnet-base-v2"

training:
  device: "auto" # "cuda" or "cpu" or "auto"
  
  # text_cleaning:
  #   lower_case: true
  #   remove_punctuation: true
  #   remove_numbers: true
  #   remove_stopwords: true

job_description:
  input_file: "job_descriptions2.csv"
  columns_to_remove: [Posting Type, "# Of Positions", Title Code No, Level, Full-Time/Part-Time indicator, Division/Work Unit, Additional Information, To Apply, Work Location 1, Recruitment Contact, Posting Date, Post Until, Posting Updated, Process Date, Salary Range From, Salary Range To, Salary Frequency, Work Location, Hours/Shift, Residency Requirement]
  qdrant_collection_name: "job_collection"
  qdrant_payload_columns: ["Job ID", "Business Title", "Job Category", "cleaned_text", "Work Location 1", "Hours/Shift"]

resume:
  input_file: "Resume.csv"
  columns_to_remove: [Resume_html]
  qdrant_collection_name: "resume_collection"
  qdrant_payload_columns: ["ID", "Category", "cleaned_text"]